apiVersion: apps/v1
kind: Deployment
metadata:
  name: roseaw-nginx-deployment
spec:
  replicas: 1  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: cithit/roseaw-nginx:latest
        ports:
        - containerPort: 80  # Expose NGINX on port 80        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  rules: 
  - host: devops0.cit.regionals.miamioh.edu
    http:
      paths:
      - path: \
        pathType: ImplementationSpecific
        backend: 
          service:
            name: nginx-internal-service
            port:
              number: 80
